name: Build Extension Package

on:
    push:
        branches: ["main", "master"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 检出源码
              uses: actions/checkout@v4

            - name: 配置 Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: 打包插件
              run: |
                  npx @vscode/vsce package --no-dependencies -o cpp-md.vsix

            - name: 上传插件
              uses: actions/upload-artifact@v4
              with:
                  name: cpp-md
                  path: cpp-md.vsix
